const courseItems = [
    //unit 1
    {"id": 1, "unitId": 1, "eng": "She is driving now, at the moment of speaking", "transl": "Она едет сейчас, в момент разговора"},
    {"id": 2, "unitId": 1, "eng": "The action is not finished", "transl": "Действие не закончено"},
    {"id": 3, "unitId": 1, "eng": "She's driving to work", "transl": "Она едет на работу"},
    {"id": 4, "unitId": 1, "eng": "I am doing something", "transl": "Я делаю что-то"},
    {"id": 5, "unitId": 1, "eng": "I'm in the middle of doing it", "transl": "Я в процессе делания"},
    {"id": 6, "unitId": 1, "eng": "I've started doing it and I haven't finished", "transl": "Я начал делать это, и я еще не закончил"},
    {"id": 7, "unitId": 1, "eng": "Please don't make so much noise, I'm working", "transl": "Пожалуйста, не шумите, я работаю"},
    {"id": 8, "unitId": 1, "eng": "She's taking a bath.", "transl": "Она принимает ванну"},
    {"id": 9, "unitId": 1, "eng": "Let's go out now, It isn't raining any more.", "transl": "Давай выйдем сейчас, дождя больше нет"},
    {"id": 10, "unitId": 1, "eng": "Steve is talking to a friend on the phone.", "transl": "Стив разговаривает с другом по телефону"},
    {"id": 11, "unitId": 1, "eng": " I'm reading a really good book at the moment.", "transl": "Я сейчас читаю действительно хорошую книгу"},
    {"id": 12, "unitId": 1, "eng": "Steve is not reading the book at the time of speaking.", "transl": "Стив не читает книгу во время разговора"},
    {"id": 13, "unitId": 1, "eng": "He means that he has started it, but has not finished it yet.", "transl": "Он имеет в виду, что он начал это, но еще не закончил"},
    {"id": 14, "unitId": 1, "eng": "Some friends of mine are building their own house.", "transl": "Некоторые мои друзья строят свой собственный дом"},
    {"id": 15, "unitId": 1, "eng": "They hope to finish it next summer", "transl": "Они надеются закончить это следующим летом"},
    {"id": 17, "unitId": 1, "eng": "You're working hard today! Yes, I have a lot to do.", "transl": "Ты сегодня усердно работаешь! Да, у меня много дел."},
    {"id": 18, "unitId": 1, "eng": "Is Sarah working this week?", "transl": "Сара работает на этой неделе?"},
    {"id": 19, "unitId": 1, "eng": "We use the present continuous when we talk about changes happening around now", "transl": "Мы используем present continuous, когда говорим об изменениях, происходящих сейчас"},
    {"id": 20, "unitId": 1, "eng": "Is your English getting better?", "transl": "Твой английский улучшается?"},
    {"id": 21, "unitId": 1, "eng": "The population of the world is rising very fast.", "transl": "Население мира растет очень быстро"},
    {"id": 22, "unitId": 1, "eng": "It's getting late.", "transl": "Становится поздно."},
    {"id": 23, "unitId": 1, "eng": "They're lying.", "transl": "Они лгут"},
    {"id": 24, "unitId": 1, "eng": "It's starting to rain", "transl": "Начинается дождь"},
    {"id": 25, "unitId": 1, "eng": "I'm getting hungry", "transl": "Я проголодался"},
    {"id": 26, "unitId": 1, "eng": "I'm looking for an apartment.", "transl": "Я ищу квартиру."},
    {"id": 27, "unitId": 1, "eng": "The company is losing money.", "transl": "Компания теряет деньги."},
    //
    {"id": 101, "unitId": 2, "eng": "We use the present simple to talk about things in general", "transl": "Мы используем настоящее простое, чтобы говорить о вещах в целом"},
    {"id": 102, "unitId": 2, "eng": "Nurses look after patients in hospitals.", "transl": "Медсестры ухаживают за пациентами в больницах."},
    {"id": 103, "unitId": 2, "eng": "I usually go away at weekends", "transl": "Я обычно ухожу на выходные"},
    {"id": 104, "unitId": 2, "eng": "The earth goes round the sun", "transl": "Земля вращается вокруг Солнца"},
    {"id": 105, "unitId": 2, "eng": "The cafe opens at 7.30 in the morning.", "transl": "Кафе открывается в 7.30 утра."},
    {"id": 106, "unitId": 2, "eng": "Where do you come from?", "transl": "Откуда ты?"},
    {"id": 107, "unitId": 2, "eng": "I don't go away very often", "transl": "Я не ухожу очень часто"},
    {"id": 108, "unitId": 2, "eng": "What does this word mean?", "transl": "Что значит это слово?"},
    {"id": 109, "unitId": 2, "eng": "Rice doesn't grow in cold climates.", "transl": "Рис не растет в холодном климате."},
    {"id": 110, "unitId": 2, "eng": "I work in a shop.", "transl": "Я работаю в магазине."},
    {"id": 111, "unitId": 2, "eng": "What do you do?", "transl": "Чем ты занимаешься?"},
    {"id": 112, "unitId": 2, "eng": "He's always so lazy", "transl": "Он всегда такой ленивый"},
    {"id": 113, "unitId": 2, "eng": "He doesn't do anything to help.", "transl": "Он не делает ничего, чтобы помочь."},
    {"id": 114, "unitId": 2, "eng": "I get up at 8 o'clock every morning.", "transl": "Я встаю в 8 часов каждое утро."},
    {"id": 115, "unitId": 2, "eng": "How often do you go to the dentist?", "transl": "Как часто вы ходите к стоматологу?"},
    {"id": 116, "unitId": 2, "eng": "Julie doesn't drink tea very often.", "transl": "Джули не пьет чай очень часто."},
    {"id": 117, "unitId": 2, "eng": "Robert usually goes away two or three times a year.", "transl": "Роберт обычно уходит два или три раза в год."},
    {"id": 118, "unitId": 2, "eng": "I promise I won't be late.", "transl": "Я обещаю, что не опоздаю."},
    {"id": 119, "unitId": 2, "eng": "Sometimes we do things by saying something.", "transl": "Иногда мы делаем что-то, говоря что-то."},
    {"id": 120, "unitId": 2, "eng": "What do you suggest I do?", "transl": "Что вы предлагаете мне сделать?"},
    {"id": 121, "unitId": 2, "eng": "Tanya speaks German very well.", "transl": "Таня очень хорошо говорит по-немецки."},
    {"id": 122, "unitId": 2, "eng": "I don't often drink coffee", "transl": "Я не часто пью кофе"},
    {"id": 123, "unitId": 2, "eng": "The swimming pool opens at 7.30 every morning.", "transl": "Бассейн открывается в 7.30 каждое утро."},
    {"id": 124, "unitId": 2, "eng": "Bad driving causes many accidents.", "transl": "Неумелое вождение становится причиной многих аварий."},
    {"id": 125, "unitId": 2, "eng": "My parents live in a very small flat", "transl": "Мои родители живут в очень маленькой квартире"},
    {"id": 126, "unitId": 2, "eng": "The Olympic Games take place every four years.", "transl": "Олимпийские игры проводятся каждые четыре года."},
    {"id": 127, "unitId": 2, "eng": "The Panama Canal connects the  Atlantic and Pacific Oceans", "transl": "Панамский канал соединяет Атлантический и Тихий океаны"},
    {"id": 128, "unitId": 2, "eng": "What time do the banks close here?", "transl": "Во сколько здесь закрываются банки?"},
    {"id": 129, "unitId": 2, "eng": "I've got a car, but I don't use it much.", "transl": "У меня есть машина, но я ею не пользуюсь."},
    {"id": 130, "unitId": 2, "eng": "Where does Ricardo come from?", "transl": "Откуда Рикардо?"},
];

//
export {courseItems as default};
